### ISSUE TITLE
"new NativeEventEmitter() was called with non-null argument without the required "addListener" method"

### ISSUE THREAD

**Issue by HugoCamposLopez** [stripe/stripe-react-native#1032]
**Describe the bug**
I am using React Native and I installed the stripe-react-native SDK.
I set it up and it is working. I followed these instructions https://stripe.com/docs/payments/accept-a-payment?platform=react-native.
But every time I start my app it keeps telling me "new NativeEventEmitter() was called with non-null argument without the required "addListener" method"

I don't know which Listener, as soon i comment //import { StripeProvider, useStripe } from "@stripe/stripe-react-native"; the warning disappear how can i fix this warning?

**To Reproduce**
I followed all instructions and as soon I open the APP I get that message.

**Expected behavior**
Not receive a warn.

**Screenshots**
![image](https://user-images.githubusercontent.com/93162852/177425590-29ef938a-b4ed-40c6-9367-e2c0a55aad4f.png)
![image](https://user-images.githubusercontent.com/93162852/177425621-7684cbc8-c4d1-4c09-8660-4fa03f48c7d0.png)

**Smartphone (please complete the following information):**
 - iPhone 11
 - OS: 15.5

**Additional context**
    "@types/react-native": "~0.66.13",
    "@stripe/stripe-react-native": "^0.12.0",
    "expo": "~45.0.0",
    expo --version
    5.4.12

**Comment by charliecruzan-stripe** [comment]
this is due to the version of stripe react native pinned in sdk 45- https://github.com/expo/expo/blob/sdk-45/packages/expo/bundledNativeModules.json#L11

you cannot use v 0.12.0 while on SDK 45. But this is fixed in a more recent version.

closing since this was fixed in https://github.com/stripe/stripe-react-native/commit/7cfcdc00bdaac7deb5836baba6ce8542bce509d7

**Comment by HugoCamposLopez** [comment]
I downgrade to     
"@stripe/stripe-react-native": "0.6.1"

iOS: Warning is gone.
Android: Still showing it.

**Comment by charliecruzan-stripe** [comment]
Ah we might be missing some blank override methods, I'll take care of that. In the meantime, you can [silence](https://stackoverflow.com/questions/69538962/new-nativeeventemitter-was-called-with-a-non-null-argument-without-the-requir/69649068#69649068) this warning if you don't want to see it

**Comment by jordzawada** [comment]
I am getting this issue on  "@stripe/stripe-react-native": "0.17.0", with SDK 45. What stripe version is recommended with SD K 45 now?

**Comment by charliecruzan-stripe** [comment]
you can use `expo install` to install the appropriate version of stripe :)

**Comment by martimarkov** [comment]
@charliecruzan-stripe has this been fixed for android? I'm 0.20.0 and still seeing this issue:

<img width="420" alt="Screenshot 2022-11-14 at 03 23 38" src="https://user-images.githubusercontent.com/1858736/201568535-499e4f2c-061e-46d1-a388-7306531ba9eb.png">

**Comment by charliecruzan-stripe** [comment]
Are you using expo?

**Comment by justinadkins** [comment]
Having the same problem on `0.21.0`. I added this to `StripeSdkModule.kt` and it resolved the issue:
```kotlin
  @ReactMethod
  fun addListener(eventName: String) {
      // Keep: Required for RN built in Event Emitter Calls.
  }

  @ReactMethod
  fun removeListeners(count: Int) {
      // Keep: Required for RN built in Event Emitter Calls.
  }
```

**Comment by textual** [comment]
Having issue on Android, not IOS using latest expo and stripe builds afaik
"@stripe/stripe-react-native": "0.19.0",
"expo": "~47.0.12",
"react": "18.1.0",
"react-native": "0.70.5"

**Comment by justinadkins** [comment]
@textual this was addressed in 0.22.0+ IIRC

**Comment by textual** [comment]
I'm using expo, so when I upgrade to the latest stripe, I get this error:

Some dependencies are incompatible with the installed expo version:
  @stripe/stripe-react-native@0.23.3 - expected version: 0.19.0
Your project may not work correctly until you install the correct versions of the packages.
Install individual packages by running npx expo install @stripe/stripe-react-native@0.19.0

not sure which is worse, expo incompatibility or andrioid not liking nativeeventemitter

**Comment by charliecruzan-stripe** [comment]
You can ignore that particularly warning with this: https://stackoverflow.com/questions/69538962/new-nativeeventemitter-was-called-with-a-non-null-argument-without-the-requir, which I would recommend instead of using a version that is not compatible with your Expo version

**Comment by Danielz2003** [comment]
> Are you using expo?

i'm using expo. same problem

**Comment by eemebarbe** [comment]
If you're on Expo and haven't built a new development build since installing stripe-react-native, this is likely your issue. Make sure you update your provisioning profile on iOS to include Apple Pay permissions before you attempt to build.
