### ISSUE TITLE
Payment Sheet - customize cursor color and "Done" button when selecting country

### ISSUE THREAD

**Issue by AldinaSculac** [stripe/stripe-react-native#1075]
Is it possible to change the cursor color (selectionColor), and the color of the "Done" button when selecting a country using Payment Sheet?

![Untitled](https://user-images.githubusercontent.com/45870393/183385505-be2884a1-d86d-47ed-a5db-91e76e3f4e77.png)

**Comment by cantide5ga** [comment]
What currently dictates the text cursor color? I haven't checked on iOS to see if this reported issue is still the case, but on Android the cursor in the Payment Sheet is always white in our app.

In an attempted workaround, I tried adding a variety of explicit entries in `android/app/src/main/res/values/styles.xml`, but no dice.

**Comment by cantide5ga** [comment]
Confirmed this is still a thing on ios.  This is so close to acceptable for our needs. Any hints @charliecruzan-stripe? I would instead consider `<CardForm>` but looking at all these issues, I'm getting mixed messages on if it's still recommended or not

**Comment by charliecruzan-stripe** [comment]
I definitely recommend the PaymentSheet over CardForm, however the tint color currently isn't customizable. but I've logged that as a feature request for our Payment Sheet Appearance module

**Comment by ChiragALogicalloop** [comment]
After I pay by card my case payment sheet opens but how to get payment details?

**Comment by cantide5ga** [comment]
@charliecruzan-stripe any updates? Per your suggestion, we've completely committed to PaymentSheet but this cursor on both platform is getting me a lot of heat. Are there any workarounds for now? Or a hint to where this can be adjusted in native code so we can fork for the time being?

**Comment by charliecruzan-stripe** [comment]
This is on the native teams' radars but work hasn't started yet. I haven't looked into where this might be able to be set in the native libraries, but working around this would mean forking both stripe-ios and stripe-android, and then forking stripe-react-native to rely on those forks

**Comment by charliecruzan-stripe** [comment]
fixed in https://github.com/stripe/stripe-ios/pull/2901, so the next version of Stripe React Native will include that!

**Comment by cantide5ga** [comment]
Sounds like we're still having an issue here, even with the latest. It might be the case this is a new custom appearance property, but I haven't seen any doc updates on it.

To be extra clear, in this specific case this is for the *blinking* input cursor on Android. 

(For others looking for the *highlight* cursor color, looks like it takes the  `color.primary` value)

**Comment by charliecruzan-stripe** [comment]
This issue is regarding iOS, can you open a new one for Android with screenshots?

**Comment by cantide5ga** [comment]
Android has been in context since my [first reply back in April](https://github.com/stripe/stripe-react-native/issues/1075#issuecomment-1513670293). But if it helps move the needle: https://github.com/stripe/stripe-react-native/issues/1547

**Comment by chocky335** [comment]
`"@stripe/stripe-react-native": "~0.35.0"`

```
const customAppearance = {
    shapes: {
      borderRadius: 8,
      borderWidth: 1,
    },
    primaryButton: {
      colors: {
        background: 'orange',
        text: '#260714',
      },
      shapes: {
        borderRadius: 24,
      },
    },
    colors: {
      icon: 'white',
      primary: 'white',
      background: '#36171F',
      primaryText: 'white',
      secondaryText: 'gray',
      componentText: 'white',
      error: 'orange',
      componentBackground: '#5C4248',
      componentBorder: '#5C4248',
      componentDivider: '#36171F',
      placeholderText: 'gray',
    },
  }
initPaymentSheet({
          merchantDisplayName: 'NAME',
          paymentIntentClientSecret: '<paymentIntentClientSecret>',
          allowsDelayedPaymentMethods: true,
          defaultBillingDetails: {
            name: '<name>',
            address: '<address>',
          },
          defaultShippingDetails: {
            name: '<name>',
            address: '<address>',
          },
          appearance: customAppearance,
          style: 'alwaysDark',
        })
```
ticker/done still have default blue color.
@charliecruzan-stripe
