### ISSUE TITLE
BECS form not working

### ISSUE THREAD

**Issue by pnogier** [stripe/stripe-react-native#652]
**Describe the bug**
Hi guys, I'm trying to implement the possibility to add BECS bank accounts for our 🇦🇺 Australian customers, but the form rendering has a kind of weird behavior,
The form appears styled completely randomly, once it will be fine, once it will be broken.
Also, I am not able to interact with the form (cannot press it, cannot type in, ...)

**To Reproduce**
Render the form : 
```javascript
const AuBecsDebitForm: React.FC<IAuBecsBankAccountFormProps> = (
    props: IAuBecsBankAccountFormProps,
): ReactElement => {
    const [formDetails, setFormDetails] = useState<AuBECSDebitFormComponent.FormDetails>();

    return (
        <View>
            <AuBECSDebitForm
                onComplete={(value) => setFormDetails(value)}
                companyName={'Archie'}
                formStyle={{
                    textColor: colors.black,
                    fontSize: 14,
                    placeholderColor: colors.grey500,
                }}
            />
        </View>
    );
};

export default AuBecsDebitForm;
```

**Expected behavior**
Have a properly styled form and be able to interact with it

**Screenshots**
<img width="415" alt="Screenshot 2021-10-16 at 11 02 32 AM" src="https://user-images.githubusercontent.com/25363506/137592775-fa70c1fa-b9fa-4430-95b7-aa644669e428.png">
<img width="420" alt="Screenshot 2021-10-16 at 11 02 21 AM" src="https://user-images.githubusercontent.com/25363506/137592776-33f3ecd4-fa43-4a2a-b23d-568859eb041c.png">
<img width="414" alt="Screenshot 2021-10-16 at 11 02 10 AM" src="https://user-images.githubusercontent.com/25363506/137592777-5f6aa04f-8142-46cd-b962-b259eb67c5d4.png">

**Desktop (please complete the following information):**
 - OS: NA
 - Browser NA
 - Version NA

**Smartphone (please complete the following information):**
 - Device: iOS Simulator
 - OS: iOS 14.5
 - Browser React Native
 - Version 0.64.2

**Additional context**
I tried it in modals from react-native-bottom-sheet and normal screens, it behaves the same way

**Comment by charliecruzan-stripe** [comment]
I believe this has been fixed in a recent release, I'm not able to reproduce this anymore using the latest version: 

https://user-images.githubusercontent.com/97612659/158411137-0914da42-3f92-4fca-a9c1-332367821ba8.mov



(sorry I can't be more specific on which release it was that fixed it). My guess is it was an underlying `stripe-ios` issue, and an update to that Pod fixed things. Let me know if you're still seeing this and how to reproduce it though!

**Comment by charliecruzan-stripe** [comment]
Sidenote- I've added support for all form styles on iOS here, which you might be interested in/find useful: https://github.com/stripe/stripe-react-native/pull/845

**Comment by pnogier** [comment]
Hi, currently back on this and I was still experiencing the same issue. 
I checked the example app and realized you were specifying a height in the `style` prop, so I did it and it fixed my issue. 
So I think that if we don't specify a height to the form, it won't render properly.
